[package]
name = "sshx"
version.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true
repository.workspace = true
documentation.workspace = true
keywords.workspace = true
edition = "2021"

[dependencies]
aes = "0.9"
aes-gcm = "0.11.0-rc.3"
ansi_term = "0.12"
anyhow.workspace = true
argon2 = { version = "0.5", default-features = false, features = ["alloc"] }
bytes = { version = "1.11", features = ["serde"] }
cfg-if = "1.0.0"
clap.workspace = true
ctr = "0.10"
encoding_rs = "0.8"
pin-project = "1.1"
base64 = "0.22"
futures-util = { version = "0.3", features = ["sink"] }
prost.workspace = true
rand.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
serde = { version = "1.0", features = ["derive"] }
sshx-core.workspace = true
tokio.workspace = true
tokio-tungstenite = { version = "0.29", features = ["rustls-tls-webpki-roots"] }
tracing.workspace = true
tracing-subscriber.workspace = true
whoami = { version = "2.1", default-features = false }

[target.'cfg(unix)'.dependencies]
close_fds = "0.3"
nix = { version = "0.31", features = ["ioctl", "process", "signal", "term"] }

[target.'cfg(windows)'.dependencies]
conpty = "0.7"
