app = 'sshx-server-sternelee'
primary_region = 'sin'
kill_signal = 'SIGINT'
kill_timeout = '1m30s'

[build]

[[services]]
  protocol = 'tcp'
  internal_port = 8051
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

    [services.ports.tls_options]
      alpn = ['h2', 'http/1.1']

  [services.concurrency]
    type = 'connections'
    hard_limit = 65536
    soft_limit = 1024

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

[[vm]]
  size = 'shared-cpu-1x'
